name: WalkThrough
favicon: null
layout_spectrum: 0.10944665945135057
typography_spectrum: 0.29828876815736294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9970310563221574
  lightness: 0.4344403906725347
  saturation: 0.10099163162522018
  rhythmicContrast: 0.8369927399326116
purpose: []
