name: Walk Through International
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee3fa'
    - '#2d60ea'
    - '#003000'
    - '#0b0066'
    - '#8db73a'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
