name: Walk Through International
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43352
title: That they may not walk alone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#100b07'
    - '#7a290b'
    - '#b28728'
    - '#e7d350'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
